general.import = [
    "~/.config/alacritty/catppuccin-grey-green.toml"
]

[font]
size = 10

[font.normal]
#family = "LiterationMono Nerd Font" #compact lines
#family = "CommitMono Nerd Font"     #compact lines
#family = "DejaVuSansM Nerd Font"    #midspaced lines
#family = "SauceCodePro Nerd Font"   #spaced lines
family = "JetBrainsMono Nerd Font"  #spaced lines
style = "Regular"

[mouse]
hide_when_typing = true

[window]
dynamic_padding = true
dynamic_title = true
opacity = 0.97

[window.padding]
x = 4
y = 4
